// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"go-ecommerce-backend-api/internal/controller"
	"go-ecommerce-backend-api/internal/repo"
	"go-ecommerce-backend-api/internal/service"
)

// Injectors from wireUser.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepo := repo.NewUserRepo()
	iUserService := service.NewUserService(iUserRepo)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
