server:
  port: 8082
databases:
  - user: admin
    password: admin
    host: localhost
    dbName: shopDev
  - user: admin2
    password: admin2
    host: localhost
    dbName: shopDev2
security:
  jwt:
    secret: secret
    expiration: 86400
redis:
  user: admin
elasticsearch:
  user: admin
rabbitmq:
  user: admin
kafka:
  user: admin